pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    docker.build('python_app', '.')
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    docker.image('python_app').inside {
                        sh 'python -m unittest discover'
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    docker.image('python_app').run('-p 5000:5000')
                }
            }
        }
    }
}